/**
 * ConfigHelper — pipeline configuration generation and display.
 *
 * Loaded with:
 *   def configHelper = load('ci/jenkins/lib/ConfigHelper.groovy')
 *
 * This file is a CpsScript. All pipeline steps (echo, sh, env, params, readJSON,
 * writeJSON, fileExists, error, etc.) are called directly — no 'steps.' prefix.
 *
 * Public API:
 *   generatePipelineConfig(configRepoPath='./config-repo')
 *     → calls scripts/lib/load-json-config.py (CI-agnostic) to produce
 *       pipeline-config.json from jdkNN_pipeline_config.json and
 *       adoptium_pipeline_config.json; sets CONFIG_* / AQA_REF / SMOKE_TESTS_PASSED
 *       env vars; returns the parsed pipelineConfig Map.
 *
 *   generateJenkinsConfig(configRepoPath='./config-repo')
 *     → calls ci/jenkins/lib/load-jenkins-json-config.py to produce a separate
 *       jenkins-config.json from jenkins_job_config.json; sets
 *       CONFIG_NODE_LABEL / CONFIG_STAGE_AGENT_LABELS env vars;
 *       returns the parsed jenkinsConfig Map.
 *
 *   summarizePipelineConfig(pipelineConfig, jenkinsConfig)
 *     → logs key build configuration values from both config objects
 */

/**
 * Generate pipeline-config.json from job parameters and the config repository.
 *
 * Loads jdkNN_pipeline_config.json and adoptium_pipeline_config.json only.
 * Does not touch jenkins_job_config.json — call generateJenkinsConfig() for that.
 *
 * Resolves BUILD_REF/AQA_REF from job params (if non-empty) or config repo defaults.
 * Sets CI-agnostic CONFIG_* environment variables for use in when{} blocks.
 *
 * @param configRepoPath  Path to the config repository root (e.g. './config-repo').
 *                        The configurations sub-directory and adoptium_pipeline_config.json
 *                        are resolved from this root automatically.
 * @return parsed pipeline-config.json as a Map (pipelineConfig)
 */
def generatePipelineConfig(String configRepoPath = './config-repo') {

    // Validate platform parameters — TARGET_OS and ARCHITECTURE are baked in by
    // the Job DSL at generation time. If either is blank the job predates the
    // current pipeline definition; it must be re-generated before running.
    if (!params.TARGET_OS?.trim()) {
        error("TARGET_OS parameter is empty. The build job must be re-generated by the launch job before running.")
    }
    if (!params.ARCHITECTURE?.trim()) {
        error("ARCHITECTURE parameter is empty. The build job must be re-generated by the launch job before running.")
    }

    // Build Python command arguments.
    // load-json-config.py reads adoptium_pipeline_config.json directly from the
    // config repo root — no ref args needed here.  Stage params (SCM_REF,
    // RUN_TESTS, etc.) flow through the Jenkins job parameter environment
    // automatically and are NOT passed to this script.
    def pythonArgs = [
        "--jdk-version jdk${params.JDK_VERSION}",
        "--variant ${params.VARIANT}",
        "--target-os ${params.TARGET_OS}",
        "--architecture ${params.ARCHITECTURE}",
        "--config-repo-path ${configRepoPath}",
        "--output-dir ."
    ]

    if (params.RELEASE_TYPE) {
        def releaseType = params.RELEASE_TYPE.toUpperCase()
        def validReleaseTypes = ['NIGHTLY', 'WEEKLY', 'RELEASE']
        if (!validReleaseTypes.contains(releaseType)) {
            error("Invalid RELEASE_TYPE: '${params.RELEASE_TYPE}'. Must be one of: ${validReleaseTypes.join(', ')} (case-insensitive)")
        }
        pythonArgs.add("--release-type")
        pythonArgs.add(releaseType)
    }

    // Execute CI-agnostic Python script — produces pipeline-config.json.
    // python-runner.sh resolves python3/python once and execs the script.
    sh "scripts/lib/python-runner.sh scripts/lib/load-json-config.py ${pythonArgs.join(' ')}"

    // Read the generated pipeline-config.json
    def pipelineConfig = readJSON(file: 'pipeline-config.json')

    // Set CI-agnostic environment variables for use in when{} blocks and by
    // stage scripts.  Only values derived from config files at init time live
    // here — stage params flow through Jenkins job parameters automatically.
    env.CONFIG_VARIANT           = pipelineConfig.buildConfig.VARIANT
    env.CONFIG_TARGET_OS         = pipelineConfig.buildConfig.TARGET_OS
    env.CONFIG_ARCHITECTURE      = pipelineConfig.buildConfig.ARCHITECTURE
    env.CONFIG_JAVA_TO_BUILD     = pipelineConfig.buildConfig.JAVA_TO_BUILD
    env.CONFIG_NODE_LABEL        = pipelineConfig.buildConfig.NODE_LABEL ?: 'worker'
    // Config-file baseline args — stage scripts merge these with EXTRA_BUILD_ARGS /
    // EXTRA_CONFIGURE_ARGS (stage params) at runtime.
    env.CONFIG_BUILD_ARGS        = pipelineConfig.buildConfig.BUILD_ARGS ?: ''
    env.CONFIG_CONFIGURE_ARGS    = pipelineConfig.buildConfig.CONFIGURE_ARGS ?: ''
    // repoDefaults — fallback refs for stage scripts when their stage params are empty
    env.CONFIG_BUILD_REF         = pipelineConfig.repoDefaults.buildRef ?: 'master'
    env.CONFIG_BUILD_REPO_URL    = pipelineConfig.repoDefaults.buildRepoUrl ?: ''
    env.CONFIG_AQA_REF           = pipelineConfig.repoDefaults.aqaRef ?: ''
    env.CONFIG_DOCKER_IMAGE      = pipelineConfig.buildConfig.DOCKER_IMAGE ?: ''
    env.CONFIG_DOCKER_REGISTRY   = pipelineConfig.buildConfig.DOCKER_REGISTRY ?: ''
    env.CONFIG_DOCKER_CREDENTIAL = pipelineConfig.buildConfig.DOCKER_CREDENTIAL ?: ''
    env.CONFIG_DOCKER_ARGS       = pipelineConfig.buildConfig.DOCKER_ARGS ?: ''
    env.CONFIG_PODMAN_ARGS       = pipelineConfig.buildConfig.PODMAN_ARGS ?: ''

    return pipelineConfig
}

/**
 * Generate jenkins-config.json from jenkins_job_config.json.
 *
 * Must be called after generatePipelineConfig() so that pipeline-config.json
 * already exists (TARGET_OS and ARCHITECTURE are read from it to resolve label
 * placeholders).  Writes a separate jenkins-config.json — pipeline-config.json
 * is never modified.
 *
 * Updates env vars:
 *   CONFIG_NODE_LABEL         — resolved Build-stage node label (with additionalNodeLabels)
 *   CONFIG_STAGE_AGENT_LABELS — JSON map of all resolved stage labels
 *
 * @param configRepoPath  Path to the config repository root (contains jenkins_job_config.json).
 * @return parsed jenkins-config.json as a Map (jenkinsConfig)
 */
def generateJenkinsConfig(String configRepoPath = './config-repo') {
    sh "scripts/lib/python-runner.sh ci/jenkins/lib/load-jenkins-json-config.py" +
       " --config-repo-path ${configRepoPath}" +
       " --pipeline-config  ./pipeline-config.json" +
       " --output           ./jenkins-config.json"

    def jenkinsConfig = readJSON(file: 'jenkins-config.json')

    // Update node label env var to the Jenkins schema-resolved Build label
    env.CONFIG_NODE_LABEL = jenkinsConfig.buildNodeLabel ?: env.CONFIG_NODE_LABEL ?: 'worker'

    // Serialise resolvedStageAgentLabels so the Jenkinsfile can resolve per-stage
    // agent labels without re-reading the config file on every agent allocation.
    // Built manually to avoid groovy.json.JsonOutput (sandbox-restricted static method).
    def labelsMap = jenkinsConfig.resolvedStageAgentLabels ?: jenkinsConfig.stageAgentLabels ?: [:]
    def labelPairs = labelsMap.collect { k, v ->
        "\"${k.replace('"', '\\"')}\":\"${v.replace('"', '\\"')}\""
    }
    env.CONFIG_STAGE_AGENT_LABELS = "{${labelPairs.join(',')}}"

    // Publish the active-node timeout so NodeAgentHelper and the Jenkinsfile
    // can enforce it at every node() allocation without re-reading config.
    env.CONFIG_ACTIVE_NODE_TIMEOUT = (jenkinsConfig.activeNodeTimeoutMinutes ?: 10).toString()

    return jenkinsConfig
}

/**
 * Display key configuration values in a consistent format.
 *
 * @param pipelineConfig  Map returned by generatePipelineConfig()
 * @param jenkinsConfig   Map returned by generateJenkinsConfig() (optional)
 */
def summarizePipelineConfig(def pipelineConfig, def jenkinsConfig = null) {
    echo "Build Configuration:"
    echo "  JDK Version: ${pipelineConfig.buildConfig.JAVA_TO_BUILD}"
    echo "  Variant: ${pipelineConfig.buildConfig.VARIANT}"
    echo "  OS: ${pipelineConfig.buildConfig.TARGET_OS}"
    echo "  Architecture: ${pipelineConfig.buildConfig.ARCHITECTURE}"
    echo "  Build Args: ${pipelineConfig.buildConfig.BUILD_ARGS}"
    echo "  Configure Args: ${pipelineConfig.buildConfig.CONFIGURE_ARGS ?: '(none)'}"
    echo "  Docker Image: ${pipelineConfig.buildConfig.DOCKER_IMAGE ?: '(none)'}"
    echo "  Docker Registry: ${pipelineConfig.buildConfig.DOCKER_REGISTRY ?: '(none)'}"
    echo "  Docker Credential: ${pipelineConfig.buildConfig.DOCKER_CREDENTIAL ?: '(none)'}"
    echo "  Docker Args: ${pipelineConfig.buildConfig.DOCKER_ARGS ?: '(none)'}"
    echo "  Podman Args: ${pipelineConfig.buildConfig.PODMAN_ARGS ?: '(none)'}"
    if (jenkinsConfig) {
        echo "Stage Agent Labels (resolved):"
        (jenkinsConfig.resolvedStageAgentLabels ?: [:]).each { stage, label ->
            echo "  ${stage}: ${label}"
        }
        echo "  Build Node Label: ${jenkinsConfig.buildNodeLabel ?: '(none)'}"
    }
}

return this
