"""
StageResolver — local pipeline equivalent of Jenkinsfile runStageScript().

Resolution order for a given stem (e.g. '13-smoke-tests'):
  1. <config_repo_root>/vendor-scripts/<stem>.sh   — vendor override (sh)
  2. <config_repo_root>/vendor-scripts/<stem>.py   — vendor override (python)
  3. <pipeline_root>/scripts/stages/<stem>.sh      — default (sh)
  4. <pipeline_root>/scripts/stages/<stem>.py      — default (python)
  5. built-in no-op                                — logs and returns 0

Stage enablement is driven by parameters in pipeline-config.json (the same
CONFIG_FILE used by stage scripts).  Mapping:

  12-validate-sbom        → buildConfig.BUILD_ARGS contains '--create-sbom'
  06-post-build-code-sign → parameters.enableSigner
  07-installer            → parameters.enableInstallers
  13-smoke-tests          → parameters.enableTests
  20-reproducible-compare → parameters.compareBuild

Stages without an explicit gate always run.
Groovy is not supported locally (Jenkins-only).

Script contracts:
  .sh  — signals failure via exit code
  .py  — signals failure via exit code

run() returns the exit code (0 = success, non-zero = failure).
Callers decide whether to raise or continue (e.g. UNSTABLE-equivalent).
"""

import json
import subprocess
from pathlib import Path


# Maps stage stems to the key in pipeline-config.json 'parameters' that gates them.
# Stages not listed here are checked by _STAGE_CONDITION, or always run.
_STAGE_PARAMETER_GATE = {
    '06-post-build-code-sign': 'enableSigner',
    '07-installer': 'enableInstallers',
    '13-smoke-tests': 'enableTests',
    '20-reproducible-compare': 'compareBuild',
}

# Stages gated by a condition evaluated against the full config (not just parameters).
# Each entry is a callable(config_dict) -> (bool, reason_str).
_STAGE_CONDITION = {
    '12-validate-sbom': lambda cfg: (
        '--create-sbom' in cfg.get('buildConfig', {}).get('BUILD_ARGS', ''),
        "parameters: --create-sbom not in BUILD_ARGS"
    ),
}


class StageResolver:
    """Resolves and executes stage scripts with vendor-override support."""

    EXTENSIONS = ['.sh', '.py']

    def __init__(self, pipeline_root: Path, config_repo_root: Path | None,
                 config_file: Path | None = None):
        """
        Args:
            pipeline_root:    Root of the ci-adoptium-pipelines checkout
                              (contains scripts/stages/).
            config_repo_root: Root of the cloned config repo (contains
                              vendor-scripts/), or None if not yet cloned.
            config_file:      Path to pipeline-config.json (generated by
                              load-json-config.py).  Used to read stage
                              enablement parameters.
        """
        self.pipeline_root = pipeline_root
        self.config_repo_root = config_repo_root
        self._config_file = config_file
        self._config: dict | None = None

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _load_config(self) -> dict:
        """Load and cache the full pipeline-config.json."""
        if self._config is None:
            if self._config_file and self._config_file.exists():
                with open(self._config_file, 'r') as f:
                    self._config = json.load(f)
            else:
                self._config = {}
        return self._config

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def is_enabled(self, stem: str) -> tuple[bool, str]:
        """
        Check whether a stage is enabled based on pipeline-config.json.

        Returns:
            (enabled, reason) — if no gate exists for this stem, returns (True, '').
        """
        # Check _STAGE_CONDITION first (full-config predicates)
        condition = _STAGE_CONDITION.get(stem)
        if condition is not None:
            enabled, reason = condition(self._load_config())
            return enabled, ('' if enabled else reason)

        # Check _STAGE_PARAMETER_GATE (parameters.* boolean flags)
        param_key = _STAGE_PARAMETER_GATE.get(stem)
        if param_key is not None:
            params = self._load_config().get('parameters', {})
            enabled = params.get(param_key, True)
            reason = '' if enabled else f"parameters.{param_key} is false in pipeline-config.json"
            return enabled, reason

        return True, ''

    def resolve(self, stem: str) -> Path | None:
        """
        Return the Path of the script to execute for *stem*, or None (no-op).

        Searches vendor-scripts/ first, then scripts/stages/.
        """
        search_roots = []
        if self.config_repo_root and self.config_repo_root.exists():
            search_roots.append(self.config_repo_root / 'vendor-scripts')
        search_roots.append(self.pipeline_root / 'scripts' / 'stages')

        for root in search_roots:
            for ext in self.EXTENSIONS:
                candidate = root / f'{stem}{ext}'
                if candidate.exists():
                    return candidate

        return None

    def run(self, stem: str, env: dict) -> int:
        """
        Resolve and execute the stage script for *stem*.

        Checks the enablement gate from pipeline-config.json first.
        Ensures TARGET_DIR exists (mirrors Jenkins runStageScript behaviour)
        before launching the script.

        Returns:
            int: exit code — 0 = success, non-zero = failure.
        """
        enabled, reason = self.is_enabled(stem)
        if not enabled:
            msg = f"ℹ️  Stage '{stem}' disabled"
            if reason:
                msg += f": {reason}"
            print(msg)
            return 0

        script = self.resolve(stem)

        if script is None:
            print(f"ℹ️  No script found for '{stem}' — stage is a no-op")
            return 0

        print(f"▶ Running {script.suffix.lstrip('.')} stage script: {script}")

        # Mirror Jenkins runStageScript: ensure TARGET_DIR exists
        target_dir = env.get('TARGET_DIR')
        if target_dir:
            Path(target_dir).mkdir(parents=True, exist_ok=True)

        if script.suffix == '.sh':
            cmd = ['bash', str(script)]
        elif script.suffix == '.py':
            cmd = ['python3', str(script)]
        else:
            raise ValueError(f"Unsupported script type: {script.suffix}")

        result = subprocess.run(cmd, env=env)
        return result.returncode
