#!/usr/bin/env python3
"""
Workspace Manager for Local Pipeline Runner

Handles workspace validation, cleanup, and directory structure management.
Extracted from run-pipeline.py to improve code organization and readability.
"""

import fnmatch
import json
import shutil
from pathlib import Path


class WorkspaceManager:
    """
    Manages workspace directories and cleanup operations for the local pipeline runner.

    Implements a three-directory architecture that mirrors Jenkins semantics:

    - stage_workspace/  : Ephemeral workspace cleaned before/after each stage.
                          WORKSPACE env var points here.  Stage scripts clone
                          repos, do work, and write outputs to TARGET_DIR
                          (a stage-specific sub-directory, e.g. build_output/).
    - build_artifacts/  : Durable archive store — the local equivalent of the
                          Jenkins artifact store.  restore_stage_inputs() copies
                          files from here into stage_workspace/ before a stage
                          (≈ copyArtifacts).  archive_stage_outputs() copies
                          TARGET_DIR back here after a stage
                          (≈ archiveArtifacts).  Persists across all stages and
                          survives --start-from-stage restarts.
    - pipeline-config.json (pipeline_workspace root): generated by Initialize,
                          immediately archived to build_artifacts/ so every
                          subsequent stage can restore it into stage_workspace/.
    """

    def __init__(self, pipeline_workspace, config_file):
        """
        Initialize workspace manager.

        Args:
            pipeline_workspace: Path to the root pipeline workspace directory
            config_file: Path to the pipeline configuration JSON file
        """
        self.pipeline_workspace = Path(pipeline_workspace).expanduser().resolve()
        self.stage_workspace = self.pipeline_workspace / 'stage_workspace'
        self.build_artifacts_dir = self.pipeline_workspace / 'build_artifacts'
        self.config_file = Path(config_file)

    def validate_and_setup(self, is_restarting, clean_requested, start_from_stage=None):
        """
        Validate workspace state and set up directory structure.

        Args:
            is_restarting: True if restarting from a specific stage
            clean_requested: True if --clean-workspace flag was provided
            start_from_stage: Name of stage to restart from (if restarting)

        Raises:
            ValueError: If workspace state is invalid for the requested operation
        """
        workspace_exists = self.pipeline_workspace.exists()

        # Validate workspace state based on operation mode
        if clean_requested and is_restarting:
            # Option conflict: can't clean workspace when restarting
            raise ValueError(
                f"ERROR: Option conflict - cannot use --clean-workspace with --start-from-stage\n"
                f"\n"
                f"When restarting from a stage, the workspace must be preserved to access\n"
                f"artifacts from previous stages. Remove --clean-workspace to continue.\n"
            )

        if is_restarting:
            # Restarting: workspace MUST exist and build_artifacts/ must be present
            if not workspace_exists:
                raise ValueError(
                    f"ERROR: Cannot restart from stage '{start_from_stage}' - workspace does not exist: {self.pipeline_workspace}\n"
                    f"\n"
                    f"When restarting from a stage, the workspace must exist with artifacts from previous stages.\n"
                    f"Run a full build first (without --start-from-stage) to create the workspace.\n"
                )
            if not self.build_artifacts_dir.exists():
                raise ValueError(
                    f"ERROR: Cannot restart from stage '{start_from_stage}' - build_artifacts/ does not exist: {self.build_artifacts_dir}\n"
                    f"\n"
                    f"The build_artifacts/ directory is required for stage restarts — it holds outputs\n"
                    f"archived by previously completed stages.\n"
                    f"Run a full build first (without --start-from-stage) to create the workspace.\n"
                )
            print(f"ℹ️  Restarting from stage '{start_from_stage}'")
            print(f"   Using existing workspace: {self.pipeline_workspace}")
            print(f"   Build artifacts store:    {self.build_artifacts_dir}")
        else:
            # Fresh build: workspace must NOT exist (unless cleaning)
            if workspace_exists:
                if not clean_requested:
                    raise ValueError(
                        f"ERROR: Workspace already exists: {self.pipeline_workspace}\n"
                        f"\n"
                        f"For a fresh build, you must either:\n"
                        f"  1. Use --clean-workspace to clean the existing workspace\n"
                        f"  2. Use --start-from-stage <stage> to restart from a specific stage\n"
                        f"  3. Manually remove the workspace directory\n"
                        f"\n"
                        f"This ensures workspace cleanliness and prevents pollution from previous runs.\n"
                    )
                # Clean the entire pipeline workspace
                print(f"⚠️  Cleaning existing workspace: {self.pipeline_workspace}")
                shutil.rmtree(self.pipeline_workspace)
                print("✅ Workspace cleaned")

            # Create workspace structure
            print(f"📁 Creating workspace structure:")
            self.pipeline_workspace.mkdir(parents=True, exist_ok=True)
            self.stage_workspace.mkdir(parents=True, exist_ok=True)
            self.build_artifacts_dir.mkdir(parents=True, exist_ok=True)
            print(f"   Pipeline workspace:  {self.pipeline_workspace}")
            print(f"   Stage workspace:     {self.stage_workspace}")
            print(f"   Build artifacts:     {self.build_artifacts_dir}")

    def cleanup_stage_workspace(self, cleanup_type):
        """
        Clean the ephemeral stage_workspace directory.

        Args:
            cleanup_type: Either 'pre' or 'post'
                - 'pre': ALWAYS cleans stage_workspace (critical for restartability)
                - 'post': Cleans stage_workspace if cleanWorkspaceAfterStage=true
        """
        if cleanup_type == 'pre':
            # Pre-cleanup: ALWAYS clean stage_workspace
            if self.stage_workspace.exists():
                print(f"🧹 Pre-cleanup: Cleaning stage workspace...")
                shutil.rmtree(self.stage_workspace)
            self.stage_workspace.mkdir(parents=True, exist_ok=True)
            print(f"   ✅ Stage workspace cleaned: {self.stage_workspace}")

        elif cleanup_type == 'post':
            # Post-cleanup: Clean if cleanWorkspaceAfterStage=true
            try:
                # Read config to check cleanWorkspaceAfterStage setting
                if self.config_file.exists():
                    with open(self.config_file, 'r') as f:
                        config = json.load(f)

                    clean_after = config.get('parameters', {}).get('cleanWorkspaceAfterStage', True)

                    if clean_after:
                        if self.stage_workspace.exists():
                            print(f"🧹 Post-cleanup: Cleaning stage workspace...")
                            shutil.rmtree(self.stage_workspace)
                            self.stage_workspace.mkdir(parents=True, exist_ok=True)
                            print(f"   ✅ Stage workspace cleaned: {self.stage_workspace}")
                    else:
                        print(f"ℹ️  Post-cleanup: Skipped (cleanWorkspaceAfterStage=false)")
            except Exception as e:
                print(f"⚠️  Warning: Post-cleanup failed: {e}")

    def archive_stage_outputs(self, stage_name, target_dir=None):
        """
        Archive TARGET_DIR → build_artifacts/.

        Local equivalent of Jenkins archiveArtifacts.  All files under
        TARGET_DIR are merged into build_artifacts/ so they are available
        to subsequent stages via restore_stage_inputs().

        Args:
            stage_name: Human-readable stage name (for logging only)
            target_dir: Path to the stage's TARGET_DIR.  Defaults to
                        stage_workspace/target/ when not specified.
        """
        target = Path(target_dir) if target_dir else self.stage_workspace / 'target'
        if not target.exists():
            rel = target.relative_to(self.stage_workspace) if target.is_relative_to(self.stage_workspace) else target
            print(f"ℹ️  Archive ({stage_name}): {rel} does not exist — nothing to archive")
            return
        if not any(target.iterdir()):
            rel = target.relative_to(self.stage_workspace) if target.is_relative_to(self.stage_workspace) else target
            print(f"ℹ️  Archive ({stage_name}): {rel} is empty — nothing to archive")
            return

        self.build_artifacts_dir.mkdir(parents=True, exist_ok=True)

        archived = 0
        for src in target.rglob('*'):
            if src.is_file():
                rel = src.relative_to(target)
                dst = self.build_artifacts_dir / rel
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst)
                archived += 1

        print(f"✅ Archive ({stage_name}): {archived} file(s) → {self.build_artifacts_dir}")

    def archive_file(self, src_path, stage_name=''):
        """
        Archive a single file directly into build_artifacts/.

        Used by the Initialize stage to archive pipeline-config.json, which
        is written to pipeline_workspace root (not TARGET_DIR) by load-json-config.py.

        Args:
            src_path: Path to the file to archive
            stage_name: Human-readable stage name (for logging only)
        """
        src = Path(src_path)
        if not src.exists():
            print(f"⚠️  Archive ({stage_name}): file not found: {src}")
            return

        self.build_artifacts_dir.mkdir(parents=True, exist_ok=True)
        dst = self.build_artifacts_dir / src.name
        shutil.copy2(src, dst)
        print(f"✅ Archive ({stage_name}): {src.name} → {self.build_artifacts_dir}")

    @staticmethod
    def _matches_pattern(rel, name, pat):
        """
        Match a file against a glob pattern using fnmatch semantics.

        Handles both flat patterns (e.g. '*.tar.gz') and path patterns
        (e.g. 'metadata/**/*') correctly.  Python's fnmatch does not treat
        '**' as a recursive wildcard, so we expand '**' into both '' and '*'
        to cover files at any depth.

        Args:
            rel:  Relative path from build_artifacts/ root, e.g. 'foo.tar.gz'
                  or 'metadata/subdir/file.json'
            name: Bare filename (Path.name), e.g. 'foo.tar.gz'
            pat:  Glob pattern, e.g. '*.tar.gz' or 'metadata/**/*'
        """
        # Direct match against full relative path or bare filename
        if fnmatch.fnmatch(rel, pat) or fnmatch.fnmatch(name, pat):
            return True
        # If pattern contains '**', expand it into both '*' (one level) and
        # '' (zero levels, i.e. collapse the separator too) and retry.
        if '**' in pat:
            for replacement in ('*', ''):
                expanded = pat.replace('**/', replacement)
                if replacement == '':
                    # Collapsed form: 'metadata/**/*' → 'metadata/*'  — avoid double-slash
                    expanded = expanded.replace('//', '/')
                if fnmatch.fnmatch(rel, expanded) or fnmatch.fnmatch(name, expanded):
                    return True
        return False

    def restore_stage_inputs(self, stage_name, artifact_filter=None):
        """
        Copy matching files from build_artifacts/ → stage_workspace/.

        Local equivalent of Jenkins copyArtifacts.  Called at the start of
        every non-Initialize stage so the stage script finds its inputs
        (pipeline-config.json, JDK tarballs, etc.) inside WORKSPACE.

        Args:
            stage_name: Human-readable stage name (for logging only)
            artifact_filter: Comma-separated list of glob patterns, e.g.
                             'pipeline-config.json,**/*.tar.gz,**/*.zip'.
                             If None or empty, all files are copied.
        """
        if not self.build_artifacts_dir.exists():
            print(f"ℹ️  Restore ({stage_name}): build_artifacts/ does not exist yet — nothing to restore")
            return

        # Build list of glob patterns
        if artifact_filter:
            patterns = [p.strip() for p in artifact_filter.split(',') if p.strip()]
        else:
            patterns = ['**/*']

        self.stage_workspace.mkdir(parents=True, exist_ok=True)

        restored = 0
        for src in self.build_artifacts_dir.rglob('*'):
            if not src.is_file():
                continue
            rel = str(src.relative_to(self.build_artifacts_dir))
            if any(self._matches_pattern(rel, src.name, pat) for pat in patterns):
                dst = self.stage_workspace / rel
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst)
                restored += 1

        print(f"✅ Restore ({stage_name}): {restored} file(s) from {self.build_artifacts_dir} → {self.stage_workspace}")

# Made with Bob
